controllers/NewsController.php
<?php

namespace app\controllers;

use app\models\Arr;
use app\models\News;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class NewsController extends Controller
{
    public function actionIndex()
    {
	    $models = new ActiveDataProvider([
            'query' => News::find()
                ->where(['active' => 1])
                ->OrderBy(['date' => SORT_DESC]),
            'sort' => false,
            'pagination' => [
                'pageSize' => 20,
            ]
        ]);

        return $this->render('index', [
            'news' => $models->getModels(),
	        'pages' => $models->getPagination(),
        ]);
    }

    public function actionView($code)
    {

        $model = News::find()->where(['code' => $code])->one();

        if ( !empty($model) ) {

            return $this->render('view', [
                'model' => $model
            ]);

        }

    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Arr;
use app\models\News;
use Yii;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
		//return $this->redirect(['/genesis.html']);
	    
	    return $this->actionGenesis();
    }
	
    public function actionGenesis ()
    {
    	global $_GET;
	
	    $models = new ActiveDataProvider([
		    'query' =>  News::find()
			    ->where(['active' =>1])
			    ->OrderBy(['date'=>SORT_DESC]),
		    'sort' => false,
		    'pagination' => [
			    'pageSize' => 15,
		    ]
	    ]);
    	
    	$viewName = 'index';
		if(\Yii::$app->devicedetect->isMobile() || $_GET['mobile'] == 'y'){
			$viewName = 'indexMobile';
		}
	
	    return $this->render($viewName, [
		    'news' => $models->getModels()
	    ]);
    }
	
	public function actionSearch ()
	{
		$query = filter_input(INPUT_GET, 'q');
		$page = filter_input(INPUT_GET, 'page' , FILTER_VALIDATE_INT);
		if(!$page){ $page = 1; }
		$onPage = 10;
		$startIndex = $onPage * $page - $onPage + 1;
		
		$apiKey = Yii::$app->params['dealer']['apiKey'];
		$searchId = Yii::$app->params['dealer']['searchId'];
		$apiUrl = 'https://www.googleapis.com/customsearch/v1?key='. $apiKey
			.'&cx='. $searchId
			.'&q='. urlencode($query)
			.'&num='. $onPage
			.'&start='. $startIndex;
		
		$error = null;
		$result = null;
		$pages = 1;
		
		$arResponse = $this->request($apiUrl, null, [
			CURLOPT_SSL_VERIFYPEER => false
		]);
		
		if($arResponse['status'] == 200){
			$result = json_decode($arResponse['response'], true);
			$total = $result['searchInformation']['totalResults'];
			$pages = intval(ceil($total / $onPage));
		}else{
			$error = "Не удалось получить результаты поиска. Попробуйте повторить позже.";
		}
		
		//echo "<pre>".var_export('<br><br><br><br><br>'.$apiUrl, true) . "</pre>";
		
		return $this->render('search', [
			'query' => $query,
			'result' => $result,
			'page' => $page,
			'pages' => $pages,
			'error' => $error,
		]);
	}
	
	/**
	 * Отправка POST запроса с использованием cURL
	 *
	 * @param string $url Адрес запроса
	 * @param array $post Массив переменных для отправки POST-запросом
	 * @param array $options Дополнительные параметры cURL
	 * @return array Массив, содержащий статус запроса и ответ сервера
	 * @throws \RuntimeException
	 */
	public function request($url, array $post = NULL, array $options = array())
	{
		$defaults = array(
			CURLOPT_URL => $url,
			CURLOPT_RETURNTRANSFER => 1,
			CURLOPT_TIMEOUT => 4,
			//CURLOPT_HEADER => 0,
			//CURLOPT_FRESH_CONNECT => 1,
			//CURLOPT_FORBID_REUSE => 1,
			//CURLOPT_POSTFIELDS => http_build_query($post)
		);
		
		if(!empty($post)){
			$defaults[CURLOPT_POSTFIELDS] = http_build_query($post);
		}
		
		$ch = curl_init();
		curl_setopt_array($ch, ($options + $defaults));
		
		$response = curl_exec($ch);
		$error    = curl_error($ch);
		$errno    = curl_errno($ch);
		$status   = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		
		if (is_resource($ch)) {
			curl_close($ch);
		}
		
		if (0 !== $errno) {
			throw new \RuntimeException($error, $errno);
		}
		
		return array(
			'status' => $status,
			'response' => $response,
		);
	}
	
    public function actionLogin()
    {
	   $this->layout = 'system';
	   
	   if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack(Yii::$app->session->get('auth_come_back'));
        } else {

            $come_back_url = Arr::get($_REQUEST,'come_back',null); var_dump($come_back_url);
            if($come_back_url)
            {
                Yii::$app->session->set('auth_come_back',$come_back_url);
            }
            else
            {
                Yii::$app->session->set('auth_come_back',null);
            }

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        $this->layout = 'system';
		Yii::$app->user->logout();

        return $this->goHome();
    }

}

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Genesis';
?>
<div id="container" class="gatemain not-hf-100per">
    <div class="inner-contain">
		<section class="kv-area js-check-height cont-fullsize" data-indicator-index="0" style="background-image: url(/images/g70/desktop/teaser-main-banner.jpg)">
			<div class="inner-cont-wrap"  data-test="1">
				<div class ="content">
					<div class="txt-holder teaser-holder">
						<div class="inner-txt" data-opacity="0,1,1,0">
							<h1 data-top="0,1,0,-150" class="teaser-title">НОВЫЙ GENESIS G70</h1>
							<div class="btns teaser-btns">
								<a href="/g70.html" class="gbtn talign-r"><span class="atxt">подробнее</span></a>
							</div>
						</div>
					</div>
				
					<span class="line"></span>
				
					<div class="btn-scroll active">
						<a href="javascript:void(0);">
							<div class="txt-area">
								<span class="btn-txt">ДАЛЬШЕ</span>
							</div>
							<br>
							<div class="line-area">
                                    <span class="vert-line-mask">
                                        <span class="vert-line"></span>
                                    </span>
							</div>
						</a>
					</div>
				</div>
			</div>
		</section>

        <section class="intro-wrap">
            <div class="inner-cont-wrap">
                <div class ="content">
                    <!-- swiper-container -->
                    <div class="swiper-container">
                        <div class="swiper-wrapper">
							<div class="swiper-slide">
								<a href="/g70.html">
                                    <span class="figure">
                                        <img src="/images/gatemain/genesis-g70-main.png" alt="g70">
                                    </span>
									<span class="figcaption">
                                        <strong>GENESIS G70</strong>
                                        <span>Подробнее</span>
                                    </span>
								</a>
							</div>
							
							<div class="swiper-slide">
                                <a href="/g80.html">
									<span class="figure">
                                    	<img src="/images/gatemain/genesis-g80-main.png" alt="g80">
									</span>
                                    <div class="figcaption">
                                        <strong>GENESIS G80</strong>
                                        <span>Подробнее</span>
                                    </div>
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="/g90.html">
									<span class="figure">
                                    	<img src="/images/gatemain/genesis-g90-main.png" alt="g90">
									</span>
                                    <div class="figcaption">
                                        <strong>GENESIS G90</strong>
                                        <span>Подробнее</span>
                                    </div>
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="/g90.html#long">
									<span class="figure">
                                    	<img src="/images/gatemain/genesis-g90l-main.png" alt="g90 L">
									</span>
                                    <div class="figcaption">
                                        <strong>GENESIS G90 L</strong>
                                        <span>Подробнее</span>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <!-- pre next btns -->
                        <a href="javascript:void(0);" class="swiper-button-prev">
                            <span class="img2"><img src="/images/common/btn_prev.png" alt="Prev"></span>
                        </a>
                        <a href="javascript:void(0);" class="swiper-button-next">
                            <span class="img2"><img src="/images/common/btn_next.png" alt="Next"></span>
                        </a>
                        <!-- //pre next btns -->
                    </div>
                    <!-- //swiper-container -->
                </div>
            </div>
        </section>

        <section class="content-wrap">
            <div class="inner-cont-wrap">
                <div class ="content">
                    <!-- tab & contents -->
                    <ul class="content-tab">
                        <li>
                            <a href="news.html">НОВОСТИ И МЕРОПРИЯТИЯ</a>
                            <div class="tab-contents">
                                <!-- tab01 swiper-container -->
                                <div class="swiper-container tab01">
									<div class="swiper-wrapper">
										
										<?php  foreach ($news as $newsItem) {
											$detailUrl = Url::toRoute(['news/view', 'code'=>$newsItem->code]);
											$date = Yii::$app->formatter->asDate($newsItem->date);
											?>
											<div class="swiper-slide">
												<a href="<?=$detailUrl?>">
													<img src="<?=$newsItem->preview_file?>" alt="<?=$newsItem->name?>">
													<div class="figcaption">
														<strong><?=$newsItem->name?></strong>
														<span class="date"><?=$date?></span>
														<p><?=$newsItem->preview_description?></p>
													</div>
												</a>
											</div>
										<? } ?>
	
	
									</div>

                                    <!-- pre next paging btns -->
                                    <div class="swiper-pagination"></div>
                                    <div class="swiper-button-wrap">
                                        <a href="javascript:void(0);" class="swiper-button-prev">
                                            <span class="img2"><img src="/images/common/btn_prev.png" alt="Назад"></span>
                                        </a>
                                        <a href="javascript:void(0);" class="swiper-button-next">
                                            <span class="img2"><img src="/images/common/btn_next.png" alt="Вперёд"></span>
                                        </a>
                                    </div>
                                    <!-- //pre next paging btns -->
                                </div>
                                <!-- //tab01 swiper-container -->
                            </div>
                        </li>
                    </ul>
                    <!-- //tab & contents -->
                </div>
            </div>
        </section>

    </div>
</div>

views/site/indexMobile.php
<?
use yii\helpers\Url;
?>
<div id="container" class="gatemain">
	<div class="inner-cont">
		<section class="cont-fullsize kv-area js-check-height" data-indicator-index="0">
			<div class="inner-cont-wrap">
				<div class="content">
					<!-- gate-swiper-wrap -->
					<div class="gate-swiper-wrap">
						<div class="swiper-container swiper-container-h">
							<!-- swiper-wrapper -->
							<div class="swiper-wrapper">
								<!-- section1 : key visual -->
								<div class="swiper-slide">
									
									<!-- kv slide -->
									<div class="swiper-container swiper-container-v">
										<div class="swiper-wrapper">
											<!-- kv01 -->
											<div class="swiper-slide">
												<div class="inner-cont-wrap">
													<div class="txt-holder">
														<div class="inner-txt">
															<h1 class="type-tit">
																<span>GENESIS</span>
															</h1>
															<div class="paragraph">
																<p>
																	Полноприводные седаны премиум-класса.
																</p>
															</div>
															
															<div class="gatemain-btn">
																<div class="gatemain-btn-wrap">
																	<a href="/configurator"><span>Конфигуратор</span></a>
																	<a href="/contacts.html"><span>Контакты</span></a>
																	<a href="/test-drive"><span>Тест-драйв</span></a>
																</div>
															</div>
														
														</div>
													</div>
													<div class="bg-holder">
														<img src="/images/gatemain/gatemain_kv.jpg" alt="" />
													</div>
													<span class="line"></span>
												</div>
											</div>
											<!-- //kv01 -->
										</div>
										<div class="swiper-pagination swiper-pagination-v"></div>
									</div>
									<!-- // kv slide -->
								
								</div>
								<!-- //section1 : key visual -->
								
								<!-- section2 : Models -->
								<div class="swiper-slide">
									<div class="intro-wrap">
										<ul class="model-list">
											<li>
												<a href="/g70.html">
													<strong>GENESIS G70</strong>
													<img src="/images/gatemain/genesis-g70-main.png" alt="G70">
												</a>
											</li>
											
											<li>
												<a href="/g80.html">
													<strong>GENESIS g80</strong>
													<img src="/images/gatemain/genesis-g80-main.png" alt="G80">
												</a>
											</li>
											<li>
												<a href="/g90.html">
													<strong>GENESIS g90</strong>
													<img src="/images/gatemain/genesis-g90-main.png" alt="G90">
												</a>
											</li>
											<li>
												<a href="/g90.html#long">
													<strong>GENESIS G90 L</strong>
													<img src="/images/gatemain/genesis-g90l-main.png" alt="G90L">
												</a>
											</li>
										</ul>
									</div>
								</div>
								<!-- //section2 : Models -->
								
								<!-- section3 : contents -->
								<div class="swiper-slide">
									<div class="contents-wrap">
										
										<ul class="contents-tab">
											<li><a href="news.html">НОВОСТИ И МЕРОПРИЯТИЯ</a></li>
										</ul>
										
										<div class="contents-list">
											<!-- NEWS & EVENT contents -->
											<div class="tab01">
												<ul class="contents-area">
													<?php  foreach ($news as $newsItem) {
														$detailUrl = Url::toRoute(['news/view', 'code'=>$newsItem->code]);
														$date = Yii::$app->formatter->asDate($newsItem->date);
														?>
														<li>
															<a href="<?=$detailUrl?>">
																<img src="<?=$newsItem->preview_file?>" alt="<?=$newsItem->name?>">
																<div class="figcaption">
																	<strong><?=$newsItem->name?></strong>
																	<span class="date"><?=$date?></span>
																	<p><?=$newsItem->preview_description?></p>
																</div>
															</a>
														</li>
													<?php }  ?>
												</ul>
            
											</div>
											
										</div>
									
									
									</div>
								</div>
								<!-- //section3 : contents -->
							</div>
							<!-- //swiper-wrapper -->
							<!-- gatemain btn-wrap-->
							<div class="gate-swiper-btn">
								<div class="swiper-pagination swiper-pagination-h"></div>
								<div class="swiper-button-next">НОВОСТИ</div>
								<div class="swiper-button-prev">МОДЕЛИ</div>
								<ul class="">
									<li></li>
									<li></li>
								</ul>
							</div>
							<!-- //gatemain btn-wrap-->
						</div>
					</div>
					<!-- //gate-swiper-wrap -->
				</div>
			</div>
		</section>
	</div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/news.php
<div class="news_announcement-top">
	<div class="news_announcement__item al-left"><a class="news_announcement__item-half news-an-img" href="news/eastern-economic-forum.html"><img src="images/econ-forum.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">19.09.2017</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/eastern-economic-forum.html">Премиальный бренд Genesis поддержал Восточный экономический форум</a></h2>
			<p class="news_announcement_desc">7 сентября 2017 года Genesis выступил официальным автомобильным партнером Восточного экономического форума, проходящего во Владивостоке 6-7 сентября. Для обеспечения транспортного обслуживания мероприятия компания предоставила организаторам форума 150 автомобилей Genesis G80.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/eastern-economic-forum.html">читать далее</a></div>
		</div>
	</div>
</div>
<div class="layout__wrapper news_announcement-content">
	<div class="news_announcement__item al-right"><a class="news_announcement__item-half news-an-img" href="news/the-hollywood-reporter.html"><img src="images/news-10.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">26.06.2017</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/the-hollywood-reporter.html">Бренд GENESIS выступил официальным автомобильным партнером вечеринки White Party журнала The Hollywood Reporter</a></h2>
			<p class="news_announcement_desc">24 июня в рамках 39-го Московского Международного кинофестиваля журнал The Hollywood Reporter собрал звезд российского кино на вечеринке White Party и вручил молодым кинематографистам ежегодную премию «Аванс». Премиальный автомобильный бренд Genesis выступил официальным партнером данного мероприятия.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/the-hollywood-reporter.html">читать далее</a></div>
		</div>
	</div>
	
	<div class="news_announcement__item al-left"><a class="news_announcement__item-half news-an-img" href="news/miss-russia-2017.html"><img src="images/miss-russia-2017-img-1.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">17.04.2017</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/miss-russia-2017.html">GENESIS И ОФИЦИАЛЬНЫЙ ДИЛЕР МАРКИ «АВИЛОН» ПОДДЕРЖАЛИ КОНКУРС «МИСС РОССИЯ 2017»</a></h2>
			<p class="news_announcement_desc">Genesis и официальный дилер марки «Авилон» выступили партнерами национального конкурса «Мисс Россия 2017», финал которого прошел 15 апреля 2017 года в концертном зале Барвиха Luxury Village.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/miss-russia-2017.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-right"><a class="news_announcement__item-half news-an-img" href="news/top-safety-pick.html"><img src="images/top-safety-pick-news-1.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">12.12.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/top-safety-pick.html">Genesis G90 получил награду Top Safety Pick+</a></h2>
			<p class="news_announcement_desc">Genesis G90 2017 модельного года получил престижную награду Top Safety Pick+ в тесте безопасности Американского страхового института дорожной безопасности (IIHS).</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/top-safety-pick.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-left"><a class="news_announcement__item-half news-an-img" href="news/context.html"><img src="images/context-news-1.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">21.11.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/context.html">Бренд Genesis поддержал гала-закрытие IV международного фестиваля современной хореографии CONTEXT. ДИАНА ВИШНЁВА</a></h2>
			<p class="news_announcement_desc">19 ноября в Санкт-Петербурге состоялось торжественное закрытие IV Международного фестиваля современной хореографии CONTEXT.Диана Вишнёва, организованного выдающейся российской балериной Дианой Вишнёвой.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/context.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-right"><a class="news_announcement__item-half news-an-img" href="news/press-release.html"><img src="images/news-8.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">15.11.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/press-release.html">Genesis поддержал гала-открытие IV международного фестиваля современной хореографии CONTEXT. ДИАНА ВИШНЁВА</a></h2>
			<p class="news_announcement_desc">14 ноября в Музыкальном театре им. К.С. Станиславского и Вл. И. Немировича-Данченко состоялось гала-открытие международного фестиваля современной хореографии CONTEXT. ДИАНА ВИШНЁВА.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/press-release.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-left"><a class="news_announcement__item-half news-an-img" href="news/vishneva.html"><img src="images/news-6.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">27.10.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/vishneva.html">Международный фестиваль современной хореографии CONTEXT. ДИАНА ВИШНЕВА</a></h2>
			<p class="news_announcement_desc">С 14 по 19 ноября 2016 года сразу в двух городах — Москве и Санкт-Петербурге — состоится международный фестиваль современной хореографии CONTEXT. ДИАНА ВИШНЁВА.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/vishneva.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-right"><a class="news_announcement__item-half news-an-img" href="news/award.html"><img src="images/award-news-1.JPG"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">20.10.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/award.html">Genesis G90 стал обладателем престижной награды для автомобилей премиум-класса</a></h2>
			<p class="news_announcement_desc">Флагманская модель Genesis признана «Лучшим седаном» на выставке роскошных автомобилей EXCS Luxury Motor Show</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/award.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-left"><a class="news_announcement__item-half news-an-img" href="news/official-partner.html"><img src="images/official-partner-news-1.JPG"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">28.09.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/official-partner.html">Новый премиальный автомобильный бренд Genesis – официальный партнер Международного инвестиционного форума «Сочи-2016»</a></h2>
			<p class="news_announcement_desc">Премиальный бренд Genesis выступит официальным автомобильным партнером XV Международного инвестиционного форума «Сочи-2016», который пройдет с 29 сентября по 2 октября 2016 года в Главном медиацентре Олимпийского парка.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/official-partner.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-right"><a class="news_announcement__item-half news-an-img" href="news/g90-launch.html"><img src="images/news-5.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">22.09.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/g90-launch.html">Премиальный бренд Genesis<br>выходит на российский рынок</a></h2>
			<p class="news_announcement_desc">22 сентября 2016 года в концертном зале «Барвиха Luxury Village» состоялась российская премьера премиального бренда Genesis.</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/g90-launch.html">читать далее</a></div>
		</div>
	</div>
	<div class="news_announcement__item al-left"><a class="news_announcement__item-half news-an-img" href="news/genesis-studio.html"><img src="images/genesis-studio-news-1.jpg"></a>
		<div class="news_announcement__item-half news-an-text"><span class="news_announcement_date">05.09.2016</span>
			<h2 class="news_announcement_title"><a class="news_announcement_title-link" href="news/genesis-studio.html">Компания Hyundai открывает в Ханаме первую в мире галерею Genesis Studio</a></h2>
			<p class="news_announcement_desc">В Корее откроется первое в мире пространство бренда Genesis</p>
			<div class="news_announcement_bottom"><a class="news_announcement_bottom-link" href="news/genesis-studio.html">читать далее</a></div>
		</div>
	</div>
</div>